version: "3.9"

services:
  api:
    container_name: acortador-api
    build:
      context: ./AcortadorURL
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__MyDatabaseConnectionString=${MY_DATABASE_CONNECTION_STRING}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3